builds:
  - binary: obbkit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto
universal_binaries:
  - replace: true
brews:
  -
   name: obbkit
   homepage: https://github.com/Onboardbase/obbkit
   tap:
    owner: Onboardbase
    name: homebrew-obbkit
   commit_author:
    name: AdeboyeDN
    email: adeboyed93@gmail.com
    