builds:
  - binary: askcloudhelloworld
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: obbkit
    homepage: https://github.com/AdeboyeDN/obbkit
    tap:
      owner: AdeboyeDN
      name: homebrew-adeboyedn
    commit_author:
      name: AdeboyeDN
      email: adeboyed93@gmail.com

checksum:
  name_template: 'checksums.txt'